name: Deploy

on:
  push:
    branches:
      - main # adjust branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20" # adjust node version as needed

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build # adjust the build script as needed

      - name: Configure Git user
        run: |
          git config --global user.email "manishranbir774@gmail.com"
          git config --global user.name "Manish Kumar"

      - name: Deploy
        run: npm run deploy
